### ISSUE TITLE
请更新暖雪修改器(有bug)

### ISSUE THREAD

**Issue by YaeSakuraQvQ** [GlossMod/UnityScriptTrainer#15]
基础功能的页面不显示 武器页面也是
只有道具功能的页面显示正常 能用
推测可能和官方的大更有关系(最近更新了新dlc等)
还有建议加上解锁宗派的大师皮肤功能...(一个个打太累了...就打了俩 白灰难度折磨人啊)
希望大佬尽快更新，plz

**Comment by 3DMXM** [comment]
已更新修复
