### ISSUE TITLE
[戴森球计划] 3.1 版本作弊器启动时遇到异常

### ISSUE THREAD

**Issue by CuteLeon** [GlossMod/UnityScriptTrainer#19]
戴森球计划版本：0.9.24
ScriptTrainer: 3.1
BepInEx: x64_5.4.21.0

按 Home 键启动作弊器时遇到如下异常：
“游戏运行错误！你可以立即另存一个存档，重启游戏看是否能恢复正常运行，如果仍然出现该错误信息，请尝试打开先前的自动存档。该信息出现时，自动存档功能将被关闭。
TypeLoadException:Could not resolve type with token 0100003e (from typeref, class/assembly UIInventoryWindow, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublickKeyToken=null)”

<img width="789" alt="image" src="https://github.com/GlossMod/UnityScriptTrainer/assets/17419770/5d3adec9-80b7-4bfb-befa-b22295afcf78">

**Comment by CuteLeon** [comment]
这个异常有可能是ScriptTrainer项目编译时所引用的UIInventoryWindow库的版本和游戏运行时真实加载的UIInventoryWindow库版本不一致，在真实加载的版本中已经移除了异常消息中提到的未能解决的类型。猜测是ScriptTrainer仅支持更早版本的戴森球计划游戏，而非我在使用的更新的0.9.24版本？

**Comment by CuteLeon** [comment]
Hi @3DMXM , 请问有时间看下吗？

**Comment by 3DMXM** [comment]
我这边没问题，我看了一下, 可能是因为你的游戏版本太低了
![图片](https://mod.3dmgame.com/static/upload/mod/202308/MOD64db501a8e79b.jpg)

**Comment by CuteLeon** [comment]
唔，我使用的是0.9.24，我升级成0.9.27试试。顺便请问你使用的BepInEx版本是什么？5.4.21.0嘛？

**Comment by 3DMXM** [comment]
BepInEx 的版本不重要, 用5.4.21就行

**Comment by CuteLeon** [comment]
测试 3.1 在 0.9.27 里可用，感谢
