### ISSUE TITLE
戴森球计划-黑雾出错

### ISSUE THREAD

**Issue by yantoumu** [GlossMod/UnityScriptTrainer#22]
![image](https://github.com/GlossMod/UnityScriptTrainer/assets/28034487/81885775-fae9-4126-a89c-0e18cf1af628)
ScriptTrainer 3.1.zip  
2023-12-18 12:31:27 55.15K 使用的这个时间的版本

https://pan.aoe.top/ScriptTrainer/Dyson_Sphere_Program

**Comment by 3DMXM** [comment]
你重新下一下 3.2 版本 https://cloud.aoe.top/s/1Vu2
