### ISSUE TITLE
太吾内置修改器v1.4显示问题

### ISSUE THREAD

**Issue by ivorkchan** [GlossMod/UnityScriptTrainer#6]
![image](https://user-images.githubusercontent.com/19368630/193075878-a8696da0-f2e9-4a7f-81ae-b0d6ca58d9c7.png)

您好，正式版（非测试分支）v0.0.18，修改器v1.4，分辨率2560，已排除其它所有模组。
从修改器v1.21开始出现这个显示问题。

**Comment by 3DMXM** [comment]
在1.4.1已经修复
