### ISSUE TITLE
MiChangSheng新增物品有Bug

### ISSUE THREAD

**Issue by qianyingchao** [GlossMod/UnityScriptTrainer#9]
ItemWindows文件，GetItemData方法在DataList分页时，int start = page * conunt 会导致下面遍历索引不是从0开始，然后有些物品搜索不到。同时maxPage = ItemData.Count / conunt会导致分页少1页。建议直接三目运算处理掉。maxPage = ItemData.Count % conunt == 0 ? ItemData.Count / conunt : ItemData.Count / conunt + 1;

还是喜欢订阅创意工坊的，不喜欢自己编译的

**Comment by 3DMXM** [comment]
已修复
